### ISSUE TITLE
Question regarding MDMOVEDS

### ISSUE THREAD

**Issue by mgrossmann** [MarkDickinson/mvs38j_utils#1]
Hi Mark,

I'm happily assembling your nice tool.
Unfortunately it could not handle HLQs with a length of 3.
Taking a look in your code, it should work with HLQ with length >2.
Any idea what could be the Problem? At [Line 228](https://github.com/MarkDickinson/mvs38j_utils/blob/a2053694f8d0ee5f9776690a1424f551d83dfcb8/mvs38j/MDMOVEDS.txt#L228) the BNH is sending me 
to the NOPARM label. But my HLQ has a length of 3. So what's wrong with R7?

Another question. Why do you compare against the value 16, then max length is 8. [Line 225](https://github.com/MarkDickinson/mvs38j_utils/blob/a2053694f8d0ee5f9776690a1424f551d83dfcb8/mvs38j/MDMOVEDS.txt#LL225) 

Thanks in advance, Mike

**Comment by MarkDickinson** [comment]
Code updated to correct the length test issue. 
On the question the compare length I allow to be 16 now rather than 8 to allow a longer compare sting (ie: PREFIX.LIB and PREFIX.PS rather than limiting it to just PREFIX). That was simply a need I had.

**Comment by mgrossmann** [comment]
Great, thanks.


/Mike
